version: '2'
services:
  elk5:
    build: elk5/
    hostname: elk5
    environment:
      ELASTIC_PASSWORD : foobar
      # otherwise logstash will keep sending its own logs to itself over and over
      LOGSPOUT: ignore
      VIRTUAL_HOST: elk.${RIT_ENV}.rit.unimaas.nl
    ports:
      - "5605:5601"
      # Expose Filebeat-ELK-port that accepts logs from non-Docker services
      #      - "5044:5044"
      # Expose Logstash-HTTP-port that accepts logs from non-Docker services
      - "5001:5001"
      # expose port for elasticsearch api's
      - "9205:9200"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./elk5/logstash-config:/etc/logstash/conf.d
      - elasticdata:/var/lib/elasticsearch
    networks:
      default:
        aliases:
          - elk5.dh.local
      corpus_default:
        aliases:
          - elk5.dh.local


networks:
  corpus_default:
    external: true

volumes:
  elasticdata: