filter {
    if "AUTH" in [tags] {

        mutate {
            add_field => { "logtrail" => "auth" }
            add_tag => [ "CP49_MUT01" ]
        }

        grok {
            break_on_match => true
            match => { "message" => "%{SYSLOGTIMESTAMP:timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: pam_unix\(%{DATA:pam_service}\): %{GREEDYDATA:log_message}" }
            match => { "message" => "%{SYSLOGTIMESTAMP:timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:log_message}" }
            add_tag => [ "CP49_GRO01" ]
        }

        # Extract user from PAM session messages
        if [pam_service] {
            grok {
                match => { "log_message" => "session %{WORD:pam_action} for user %{USERNAME:auth}\(uid=%{INT:auth_uid}\)" }
                tag_on_failure => []
                add_tag => [ "CP49_GRO02" ]
            }
        }

        date {
            timezone => "Europe/Amsterdam"
            match => [ "timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
            remove_field => [ "timestamp" ]       # cleanup, data is available in @timestamp
            add_tag => [ "CP49_DAT01" ]
        }
    }
}
