filter {
   if [type] == "dockerlogs" {
    if "SOLRPROXY" in [tags] {
          mutate {
            add_field => {
                "logtrail" => "solrproxy"
                "source" => "dockerlogs"
            }
          }
     }
  } 
}
